modLoader="javafml"
loaderVersion="[24,)"
[[mods]]
modId="allowcolor"
version="2.0"
displayName="AllowColor Mod"
displayURL="https://github.com/DawningW/Allow-Color-Mod"
credits="Mojang, FML and Forge"
authors="QingChenW"
description='''
Type color codes in Minecraft.
'''
[[dependencies.allowcolor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.allowcolor]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
